apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  labels:
    app: back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      name: backend-pod
      labels:
        app: back
    spec:
      containers:
        - name: back-c1
          image: lokesh258/back-3:3
          ports:
            - containerPort: 3001
          env:
            - name: DATABASE_URL
              value: "mongodb://mongo-service:27016"
            

---
apiVersion: v1
kind: Service
metadata:
  name: backend-servicess
  labels:
    app: back
spec:
  type: LoadBalancer
  selector:
    app: back
  ports:
    - port: 3004
      targetPort: 3001


