apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      name: mongo-pod
      labels:
        app: mongo 
    spec:
      containers:
      - name: mongo-c1
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGODB_INITDB_ROOT_USERNAME
          value: "username"
        - name: MONGODB_INITDB_ROOT_PASSWORD
          value: "password"
            

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: mongo
spec:
  type: LoadBalancer
  selector:
    app: mongo
  ports:
    - port: 27016
      targetPort: 27017 
  


